[env]
NEOCITIES_MISE_ACTIVE = "true"

[settings]
env_file = '.env'

[tools]
'gem:neocities' = { version = 'latest' }

[tasks]
'push' = { run = 'neocities push --prune src/' }
'info' = { run = 'neocities info' }
'pull' = { run = 'neocities pull' }
